### 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

In [2]:
#random no.
a= np.random.random((3,3,3))
a

array([[[0.58329179, 0.94947945, 0.22280689],
        [0.54637931, 0.34664688, 0.55086246],
        [0.74143691, 0.94339013, 0.62443215]],

       [[0.25549627, 0.87174086, 0.71461672],
        [0.84502858, 0.99131677, 0.33619891],
        [0.21337777, 0.11843032, 0.11220554]],

       [[0.42556192, 0.12102602, 0.92891825],
        [0.97387205, 0.63756695, 0.07040182],
        [0.48106177, 0.28545416, 0.43475747]]])

### 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal:

In [3]:
matrix_5x5 = np.diag([1,2,3,4], k=-1)
print(matrix_5x5)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
matrix_8x8 = np.zeros((8,8),dtype=int)
matrix_8x8[1::2,::2] = 1
matrix_8x8[::2,1::2] = 1
print(matrix_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 4. Normalize a 5x5 random matrix

In [9]:
random_matrix = np.random.random((5,5))
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print(normalized_matrix)


[[0.56788117 0.47841301 0.5157562  0.         0.89696784]
 [0.44214891 0.62703828 0.97669918 0.03750814 0.2319318 ]
 [0.5588379  0.31751126 0.79209673 0.48039084 0.64113509]
 [0.03689905 0.56426316 0.39092278 0.12794978 1.        ]
 [0.6975406  0.57069621 0.79025639 0.73603359 0.56334826]]


### 5. How to find common values between two arrays?


In [5]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([4,5,6,7,8])
common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5]


### 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
from datetime import datetime, timedelta

today = datetime.today().date()
yesterday = today - timedelta(1)
tomorrow = today + timedelta(1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


### 7. Consider two random array A and B, check if they are equal


In [10]:
A = np.random.rand(5,5)
B = np.random.rand(5,5)
are_equal = np.array_equal(A, B)
print(are_equal)


False


### 8.Create random vector of size 10 and replace the maximum value by 0


In [13]:
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

[0.19734781 0.53239974 0.25902079 0.44959443 0.29319819 0.77458505
 0.02758318 0.70907972 0.         0.43703834]


### 9. How to print all the values of an array?


In [14]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ravel())

[1 2 3 4 5 6 7 8 9]


`ravel()` returns a flattened array. Alternatively, you can simply use `print(array)` to print the array in its current shape.


### 10.Subtract the mean of each row of a matrix

In [15]:
matrix = np.random.rand(5,5)
mean_subtracted = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted)

[[ 0.35746182 -0.06785539  0.03610815 -0.15551872 -0.17019587]
 [-0.31347999 -0.22398975  0.53081658  0.15887764 -0.15222448]
 [-0.26593185  0.32937506  0.08881991 -0.15137728 -0.00088584]
 [ 0.29795098 -0.01164752 -0.07566942 -0.05274522 -0.15788883]
 [-0.16087492  0.20141019  0.00665184 -0.23190902  0.18472192]]


### 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?



In [16]:
vector = np.array([1,2,3,4,5,6,7,8,9,10])
indices = np.array([1,3,3,5])
np.add.at(vector, indices, 1)
print(vector)


[ 1  3  3  6  5  7  7  8  9 10]


### 12.How to get the diagonal of a dot product


In [17]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)
print(diagonal)


[0.7133309  0.4143775  0.79647262]
